server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    # ispravan MIME za .ics
    types {
        text/calendar  ics;
    }

    # poslužuj .ics bez cachea (po želji)
    location ~* \.ics$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files $uri =404;
    }

    # nema index stranice; sve ostalo 404
    location / {
        try_files $uri $uri/ =404;
    }
}
